#!/bin/bash
if [ "$1" == '-h' ] || [ "$1" == '--help' ]
then
	echo "9blanc"
	echo "======"
	echo
	echo "Règles"
	echo "------"
	echo -e "Une case est blanche (\e[47;30m.\e[m) ou noire (\e[40;37m.\e[m)."
	echo "À gauche est le plateau de jeu, à droite les contôles."
	echo "Deux cases sont dites adjacentes si elles sont reliées par un trait."
	echo "Appuyer sur une case l'inverse ainsi que toutes celles adjacentes."
	echo "La victoire s'obtient en blachissant toutes les cases."
	echo "La touche 'E' permet de quitter le jeu à tout moment."
	echo
	echo "Controles"
	echo "---------"
	echo 'V-D-L-J'
	echo '| | | |'
	echo 'T-S-R-N'
	echo '| | | |'
	echo 'Q-G-H-F'
	echo
	echo "Bon jeu !"
	exit 0
fi

clear
old_stty=$(stty -g)
stty -icanon

#Plateau
tput cup 0 0
echo
echo '         9-BLANC'
echo '         Coups : '
echo '         0'
echo
echo '         [ ]     '

#Coordonnées
parc='0 1 2 3 4 5 6 7 8 9 10 11'
x=(0 2 4 6 0 2 4 6 0 2 4 6)
y=(0 0 0 0 2 2 2 2 4 4 4 4)
coups=0

#Constantes d’affichage
ca_no(){
	tput cup $1 $2
	echo -en '\e[40;37m \e[m'
	tput cup "$(( $1+1 ))" $2
	echo -en '\e[40;37m.\e[m'
	tput cup $1 "$(( $2+1 ))"
	echo -en '\e[40;37m \e[m'
	tput cup "$(( $1+1 ))" "$(( $2+1 ))"
	echo -en '\e[40;37m \e[m'
}
ca_bl(){
	tput cup $1 $2
	echo -en '\e[47;30m \e[m'
	tput cup "$(( $1+1 ))" $2
	echo -en '\e[47;30m.\e[m'
	tput cup $1 "$(( $2+1 ))"
	echo -en '\e[47;30m \e[m'
	tput cup "$(( $1+1 ))" "$(( $2+1 ))"
	echo -en '\e[47;30m \e[m'
}

#Initialisation
cases=()
for i in $parc
do
	if [ $[($RANDOM % 2) + 1] = 1 ]
	then
		cases[$i]=0
		ca_bl ${y[$i]} ${x[$i]}
	else
		cases[$i]=1
		ca_no ${y[$i]} ${x[$i]}
	fi
done

#Boucle principale
continuer=true
while $continuer
do
	#Action
	tput cup 5 10
	read -n 1 touche
	case $touche in
		'v')
			aInverser='0 1 4'
		;; 'd')
			aInverser='0 1 2 5'
		;; 'l')
			aInverser='1 2 3 6'
		;; 'j')
			aInverser='2 3 7'
		;; 't')
			aInverser='0 4 5 8'
		;; 's')
			aInverser='1 4 5 6 9'
		;; 'r')
			aInverser='2 5 6 7 10'
		;; 'n')
			aInverser='3 6 7 11'
		;; 'q')
			aInverser='4 8 9'
		;; 'g')
			aInverser='5 8 9 10'
		;; 'h')
			aInverser='6 9 10 11'
		;; 'f')
			aInverser='7 10 11'
		;; 'e')
			aInverser=''
			continuer=false
		;; *)
			aInverser=''
	esac
	
	#Compteur
	if [ -n "$aInverser" ]
	then
		(( coups++ ))
	fi
	
	#Affichage et inversion
	for i in $aInverser
	do
		cases[$i]=$[1 - ${cases[i]}]
		if [ ${cases[$i]} -eq 0 ]
		then
			ca_bl ${y[$i]} ${x[$i]}
		else
			ca_no ${y[$i]} ${x[$i]}
		fi
	done
	tput cup 3 9
	echo -n "$coups"
	
	#Vérification
	if [ "${cases[*]}" = "0 0 0 0 0 0 0 0 0 0 0 0" ]
	then
		echo -en '\e[47;30m'
		tput cup 6 0
		echo '  '
		sleep 0.2
		tput cup 6 2
		echo 'V '
		sleep 0.2
		tput cup 6 4
		echo 'I '
		sleep 0.2
		tput cup 6 6
		echo 'C '
		sleep 0.2
		tput cup 6 8
		echo 'T '
		sleep 0.2
		tput cup 6 10
		echo 'O '
		sleep 0.2
		tput cup 6 12
		echo 'I '
		sleep 0.2
		tput cup 6 14
		echo 'R '
		sleep 0.2
		tput cup 6 16
		echo 'E '
		echo -en '\e[m'
		continuer=false
	fi
done

#Fin
tput cup 7 0
stty "$old_stty"
exit 0
