#!/bin/bash
###### AQUARIUM : politesse codifiée
# Written by Quentin RIBAC (2016)
# This is free software.
# See LICENSE file for legal information.

##### Constantes utilisées
span_max=3600
span_min=`bc <<< "$span_max*0.1/1"`
span_danger=`bc <<< "$span_max*0.9/1"`

##### Récupération de la date de dernier appel (dernière ligne de ce fichier)
lastdate="$(tail -n 1 $0)"

##### Récupération de la date actuelle
now="$(date +%s)"

##### Écart
(( span=now-lastdate ))

if [ "$1" == '--state' ] || [ "$1" == '-s' ]
then
	if [ "$span" -lt "$span_min" ]
	then
		# Joie : plus de 90% du temps restant
		echo -n "\\(^_^)/"
	elif [ "$span" -lt "$span_danger" ]
	then
		# État normal : de 10% à 90% du temps restant
		echo -n "<(n_n)>"
	elif [ "$span" -lt "$span_max" ]
	then
		# Danger imminent : moins de 10% du temps restant
		echo -n ".(ó_ò)."
	else
		# En attente grave d’aquarium : temps dépassé
		echo -n "/(;_;)\\"
	fi
	exit 0
elif [ "$1" == '--params' ] || [ "$1" == '-p' ]
then
	echo "$span_min/$span_danger/$span_max — $span"
	exit 0
fi

##### Écriture de la date actuelle
sed -i '$ d' $0 && echo "$now" >> $0

##### Commentaire
if [ "$span" -lt "$span_min" ]
then
	echo "Non mais c’est bon, attends un peu $(bc -l <<< "$span_min - $span") secondes de plus que ça !"
elif [ "$span" -lt "$span_max" ]
then
	echo "Ça fait $span secondes, merci bien."
else
	echo "$(bc -l <<< "$span - $span_max") secondes de retard ? Tu traînes, je trouve."
fi

###### Fin de l’exécution
exit 0

###### Date de dernier appel
1505296816
