#!/bin/bash
dims="$(xrandr -q | grep -oe 'current [[:digit:]]* x [[:digit:]]*' | sed 's/current //;s/ x /\n/')"
w="$(head -n 1 <<< "$dims")"
h="$(head -n 2 <<< "$dims" | tail -n 1)"
iw="$((w/50))"
ih="$((h/50))"

ctr="$(head -c 3 /dev/random)"
for ((y=0; y < ih; y++))
do
	for ((x=0; x < iw; x++))
	do
		if [ $(( (x - (iw/2))**2 + (y - (ih/2))**2 < ih/2)) == 1 ]
		then
			echo -n "$ctr"
		else
			head -c 3 /dev/random
		fi
	done
done | display -backdrop -window root -sample "${w}x${h}" -depth 8 -size "${iw}x${ih}" RGB:-
