#!/bin/bash
# status string for dwm

# time
xrootname="$(hf -c)"

# date and uptime in days
jours=( "di" "lu" "ma" "me" "je" "ve" "sa" )
xrootname+=" ${jours[$(date '+%w')]}$(date '+%d%m%y')"
xrootname+="/$(bc <<< "($(date '+%s') - $(date -d "$(uptime -s)" '+%s')) / 86400")"

# connection status
co="$(nmcli -t g | cut -d: -f1)"
if [ "${co%nnected}" == 'co' ]
then
	xrootname+=" @ok"
else
	xrootname+=" @:("
fi

# cpu load
xrootname+=" l$(cat /proc/loadavg | cut -d' ' -f2)"

# cpu temperature
xrootname+=" c$(acpi -V | grep 'degrees' | head -n 1 | egrep -o '[[:digit:]]+.[[:digit:]]')"

# sound volume
xrootname+=" v$(amixer -c 1 | egrep -o 'Playback .* \[...?%\]' | sed -r 's/Playback .* \[(...?)%\]/\1/' | head -n 1)"

# aquarium
xrootname+=" $(aquarium -s)"

# display this
echo " ${xrootname} "

# Kraken BTC-EUR
#xrootname+=" x$(curl 'https://api.kraken.com/0/public/Ticker?pair=xbteur' 2> /dev/null | jq '.result.XXBTZEUR.c[0]' | colrm 1 1 | colrm 5)"

# Backlight
#xrootname+=" b$(xbacklight -get | cut -d'.' -f1)"
